export const ALL_LIST = [
    {
      "videoid": "cf4cf441",
      "title": "Hold Tight",
      "director": ["Harlan Coben"],
      "cast": [
        "Magdalena Boczarska",
        "Leszek Lichota",
        "Krzysztof Oleksyn",
        "Agnieszka Grochowska",
        "Grzegorz Damięcki",
        "Agata Łabno",
        "Dominika Krzemińska",
        "Klementyna Karnkowska",
        "Justyna Wasilewska",
        "Jacek Poniedziałek",
        "Julia Wyszyńska",
        "Adam Nawojczyk",
        "Mikołaj Śliwa",
        "Jakub Pruski",
        "Wiktoria Gorodeckaja",
        "Marta Piętka"
      ],
      "type": "Limited Series",
      "description": "When a young man goes missing soon after his friend dies, life in a tight-knit, affluent Warsaw suburb slowly unravels, exposing secrets and lies. This engrossing thriller series is based on the Harlan Coben novel of the same name.",
      "chinese": "什麼都別說",
      "tags_no": [108911, 100055],
      "genres_no": [81422107, 4366, 26146]
    },
    {
      "videoid": "7023c002",
      "title": "13 Commandments",
      "director": [],
      "cast": [
        "Dirk Van Dijck",
        "Marie Vinck",
        "Karlijn Sileghem",
        "Bert Haelvoet",
        "Tom Ternest",
        "Ella Leyers",
        "Line Pillet",
        "Katelijne Verbeke",
        "Lola Rose Delany",
        "Gökhan Girginol",
        "Koen Van Impe"
      ],
      "type": "1 Season",
      "description": "Thou shalt not kill. But thou can mete out poetic justice with maximum cruelty -- if thou is a vicious serial attacker.",
      "chinese": "十三誡",
      "tags_no": [108910, 100044],
      "genres_no": [81427743, 4366, 26146]
    },
    {
      "videoid": "a76eb312",
      "title": "Ouija",
      "director": ["Stiles White"],
      "cast": [
        "Olivia Cooke",
        "Ana Coto",
        "Daren Kagasoff",
        "Bianca A. Santos",
        "Douglas Smith",
        "Shelley Hennig",
        "Sierra Heuermann",
        "Lin Shaye",
        "Vivis Colombetti",
        "Sunny May Allison"
      ],
      "type": "1h 29m",
      "description": "When their friend mysteriously dies, grieving teens seek connection via an antique ouija board that conjures up a nightmare from the other side.",
      "chinese": "碟仙",
      "tags_no": [1159493, 8711],
      "genres_no": [1159493, 8711]
    },
    {
      "videoid": "f871de48",
      "title": "Brokeback Mountain",
      "director": ["Ang Lee"],
      "cast": [
        "Heath Ledger",
        "Jake Gyllenhaal",
        "Michelle Williams",
        "Linda Cardellini",
        "Anna Faris",
        "Anne Hathaway",
        "Randy Quaid",
        "Graham Beckel",
        "Scott Michael Campbell",
        "David Harbour",
        "Kate Mara"
      ],
      "type": "2h 14m",
      "description": "Their love was forbidden. Their passion was real. Their torment took them through a lifetime of joy and bitterness.",
      "chinese": "斷背山",
      "tags_no": [5977, 1159493, 7700, 9889, 5763],
      "genres_no": [5977, 1159493, 7700]
    },
    {
      "videoid": "84d64524",
      "title": "Stranger Things",
      "director": ["The Duffer Brothers"],
      "cast": [
        "Winona Ryder",
        "David Harbour",
        "Millie Bobby Brown",
        "Finn Wolfhard",
        "Gaten Matarazzo",
        "Caleb McLaughlin",
        "Noah Schnapp",
        "Sadie Sink",
        "Natalia Dyer",
        "Charlie Heaton",
        "Joe Keery",
        "Maya Hawke",
        "Brett Gelman",
        "Priah Ferguson",
        "Dacre Montgomery",
        "Cara Buono",
        "Matthew Modine",
        "Paul Reiser",
        "Sean Astin",
        "Shannon Purser"
      ],
      "type": "3 Seasons",
      "description": "This eerie homage to '80s classics boasts a \"Spielbergian sense of wonder and a John Hughes-like knack for underage anthropology\" (The New Yorker).",
      "chinese": "怪奇物語",
      "tags_no": [108911, 100053],
      "genres_no": [3300242, 60951, 83059]
    },
    {
      "videoid": "d03230c6",
      "title": "The Stranger",
      "director": ["Harlan Coben"],
      "cast": [
        "Richard Armitage",
        "Siobhan Finneran",
        "Jennifer Saunders",
        "Shaun Dooley",
        "Paul Kaye",
        "Dervla Kirwan",
        "Kadiff Kirwan",
        "Hannah John-Kamen",
        "Anthony Head",
        "Stephen Rea",
        "Jacob Dudman",
        "Ella-Rae Smith",
        "Brandon Fellows",
        "Misha Handley"
      ],
      "type": "Limited Series",
      "description": "A stranger approaches Adam Price with a disturbing allegation about his wife, Corinne. Meanwhile, detectives Johanna and Wes take on a bizarre case.",
      "chinese": "陌生人",
      "tags_no": [100055],
      "genres_no": [4366, 26146, 81399656]
    },
    {
      "videoid": "510ab3c5",
      "title": "The Valhalla Murders",
      "director": ["Thordur Palsson"],
      "cast": [
        "Nína Dögg Filippusdóttir",
        "Björn Thors",
        "Bergur Ebbi",
        "Aldís Amah Hamilton",
        "Sigurður Skúlason",
        "Tinna Hrafnsdóttir",
        "Arndís Hrönn Egilsdóttir",
        "Edda Björgvinsdóttir",
        "Valur Freyr Einarsson",
        "Damon Younger"
      ],
      "type": "1 Season",
      "description": "An Oslo detective with a painful past returns to his native Iceland to help a dedicated cop hunt a serial killer with a link to a mysterious photo.",
      "chinese": "瓦爾哈拉連續殺人事件",
      "tags_no": [100037, 100055],
      "genres_no": [4366, 26146, 76802]
    },
    {
      "videoid": "78331f6b",
      "title": "The Woods",
      "director": ["Harlan Coben"],
      "cast": [
        "Grzegorz Damięcki",
        "Agnieszka Grochowska",
        "Hubert Miłkowski",
        "Wiktoria Filus",
        "Jacek Koman",
        "Krzysztof Zarzecki",
        "Ewa Skibińska",
        "Martyna Byczkowska",
        "Roman Gancarczyk",
        "Adam Wietrzyński"
      ],
      "type": "1 Season",
      "description": "In 1994, a summer camp reels from a brutal crime. Twenty-five years later, the police seek prosecutor Paweł Kopiński's help identifying a murder victim.",
      "chinese": "第 43 個祕密",
      "tags_no": [108911, 100037, 100055],
      "genres_no": [81422107, 4366, 26146]
    },
    {
      "videoid": "b4c05917",
      "title": "Ratched",
      "director": ["Evan Romansky"],
      "cast": [
        "Sarah Paulson",
        "Finn Wittrock",
        "Judy Davis",
        "Sharon Stone",
        "Cynthia Nixon",
        "Jon Jon Briones",
        "Charlie Carver"
      ],
      "type": "1 Season",
      "description": "Nurse Mildred Ratched seeks employment at Lucia State Hospital as it prepares to admit a new psychiatric patient: notorious killer Edmund Tolleson.",
      "chinese": "拉契特：黯衣天使",
      "tags_no": [108911, 100037],
      "genres_no": [34028, 1819174, 89811]
    },
    {
      "videoid": "640f8025",
      "title": "How to Get Away With Murder",
      "director": ["Peter Nowalk"],
      "cast": [
        "Viola Davis",
        "Billy Brown",
        "Alfred Enoch",
        "Jack Falahee",
        "Katie Findlay",
        "Aja Naomi King",
        "Matt McGorry",
        "Karla Souza",
        "Charlie Weber",
        "Liza Weil"
      ],
      "type": "6 Seasons",
      "description": "A law professor gives her students a shot at some real-world cases. Too bad that includes embroiling them in murder.",
      "chinese": "謀殺入門課",
      "tags_no": [100055],
      "genres_no": [4366, 26146, 25801]
    },
    {
      "videoid": "e3076224",
      "title": "Tabula Rasa",
      "director": ["Malin-Sarah Gozin", "Veerle Baetens"],
      "cast": [
        "Veerle Baetens",
        "Stijn Van Opstal",
        "Jeroen Perceval",
        "Hilde Van Mieghem",
        "Gene Bervoets",
        "Peter Van den Begin",
        "Natali Broods"
      ],
      "type": "1 Season",
      "description": "Mie, who has amnesia, finds herself in a locked psych ward, where a detective questions her about the recent disappearance of a man she was seen with.",
      "chinese": "心如白紙",
      "tags_no": [100049, 108911],
      "genres_no": [81427743, 4366, 89811]
    },
    {
      "videoid": "e7912e03",
      "title": "Light the Night",
      "director": ["Lien Yi-chi"],
      "cast": [
        "Ruby Lin",
        "Tony Yang",
        "Cheryl Yang",
        "Rhydian Vaughan",
        "Derek Chang",
        "Esther Liu",
        "Cherry Hsieh",
        "Nikki Hsieh",
        "Puff Kuo",
        "Cammy Chiang",
        "Hu Wei-jie",
        "Nash Zhang"
      ],
      "type": "3 Parts",
      "description": "This 2021 drama thriller series features Ruby Lin, Tony Yang and Cheryl Yang.",
      "chinese": "華燈初上",
      "tags_no": [100037, 100055],
      "genres_no": [81417804, 4366, 26146]
    },
    {
      "videoid": "694d1c0e",
      "title": "Black Mirror",
      "director": ["Charlie Brooker"],
      "cast": [
        "Jesse Plemons",
        "Cristin Milioti",
        "Jimmi Simpson",
        "Michaela Coel",
        "Rosemarie DeWitt",
        "Douglas Hodge",
        "Andrea Riseborough",
        "Brenna Harding",
        "Owen Teague",
        "Andrew Gower",
        "Kiran Sonia Sawar",
        "Georgina Campbell",
        "Joe Cole",
        "Maxine Peake",
        "Jake Davies",
        "Clint Dyer",
        "Letitia Wright",
        "Babs Olusanmokun",
        "Bryce Dallas Howard",
        "Alice Eve",
        "Michael Kelly",
        "Cherry Jones",
        "Gugu Mbatha-Raw",
        "Mackenzie Davis",
        "Wyatt Russell",
        "Benedict Wong",
        "Kelly Macdonald",
        "Faye Marsay",
        "Madeline Brewer",
        "Hannah John-Kamen",
        "Malachi Kirby",
        "Alex Lawther",
        "Jerome Flynn",
        "James Norton",
        "Rory Kinnear",
        "Lindsay Duncan",
        "Daniel Kaluuya",
        "Jessica Brown Findlay",
        "Rupert Everett",
        "Toby Kebbell",
        "Jodie Whittaker",
        "Hayley Atwell",
        "Domhnall Gleeson",
        "Lenora Crichlow",
        "Michael Smiley",
        "Daniel Rigby",
        "Chloe Pirrie",
        "Jason Flemyng",
        "Jon Hamm",
        "Oona Chaplin",
        "Rafe Spall",
        "Anthony Mackie",
        "Yahya Abdul-Mateen II",
        "Tammy Brown",
        "Andrew Scott",
        "Damson Idris",
        "Topher Grace",
        "Miley Cyrus",
        "Madison Davenport",
        "Angourie Rice"
      ],
      "type": "5 Seasons",
      "description": "The sleek world of tomorrow offers opportunities beyond our wildest dreams. At a price out of our worst nightmares.",
      "chinese": "黑鏡",
      "tags_no": [100049, 108910],
      "genres_no": [81399656, 3300242, 89811]
    },
    {
      "videoid": "5e2ca520",
      "title": "Behind Her Eyes",
      "director": [],
      "cast": [
        "Simona Brown",
        "Eve Hewson",
        "Tom Bateman",
        "Robert Aramayo",
        "Tyler Howitt",
        "Georgie Glen"
      ],
      "type": "Limited Series",
      "description": "A spilled drink at a bar leads to an awkward day at work for Louise, who's shaken again by night terrors. David introduces Adele to his new colleagues.",
      "chinese": "三人要守密，兩人得死去",
      "tags_no": [100049, 108911],
      "genres_no": [4366, 81399656, 1819174]
    },
    {
      "videoid": "63ea4486",
      "title": "Unbelievable",
      "director": [],
      "cast": [
        "Toni Collette",
        "Merritt Wever",
        "Kaitlyn Dever",
        "Dale Dickey",
        "Scott Lawrence",
        "Danielle Macdonald",
        "Austin Hébert",
        "Eric Lange",
        "Elizabeth Marvel"
      ],
      "type": "Limited Series",
      "description": "As a traumatized young woman reports being raped by an intruder, she faces a whirlwind of emotions -- and increasingly skeptical questions from police.",
      "chinese": "難，置信",
      "tags_no": [100039],
      "genres_no": [26146, 11714, 72404]
    },
    {
      "videoid": "b2fd236d",
      "title": "Trial By Media",
      "director": [],
      "cast": [],
      "type": "1 Season",
      "description": "A man reveals his crush to a straight friend on \"The Jenny Jones Show.\" Days later a murder occurs, leading to questions about the show's culpability.",
      "chinese": "媒體公審",
      "tags_no": [108393],
      "genres_no": [108393]
    },
    {
      "videoid": "a8bc6712",
      "title": "The Ripper",
      "director": ["Ellena Wood", "Jesse Vile"],
      "cast": [],
      "type": "Limited Series",
      "description": "In the 1970s, the brutal murders of sex workers in economically depressed areas of the UK spark little public interest — until a teen is also killed.",
      "chinese": "約克郡開膛手",
      "tags_no": [3053904],
      "genres_no": [3053904]
    },
    {
      "videoid": "834af1f2",
      "title": "Seven",
      "director": ["Sergei Bodrov"],
      "cast": [
        "Jeff Bridges",
        "Ben Barnes",
        "Julianne Moore",
        "Alicia Vikander",
        "Antje Traue",
        "Olivia Williams",
        "John DeSantis",
        "Kit Harington",
        "Djimon Hounsou",
        "Gerard Plunkett",
        "Jason Scott Lee"
      ],
      "type": "1h 42m",
      "description": "When good and evil collide, it will take a special warrior to intervene. And he'll need to hone his exorcism skills.",
      "chinese": "火線追緝令",
      "tags_no": [1159493, 9889, 1365],
      "genres_no": [9994, 1159493, 5824]
    },
    {
      "videoid": "22fb0f10",
      "title": "Money Heist",
      "director": ["Álex Pina"],
      "cast": [
        "Úrsula Corberó",
        "Álvaro Morte",
        "Itziar Ituño",
        "Pedro Alonso",
        "Miguel Herrán",
        "Jaime Lorente",
        "Esther Acebo",
        "Darko Perić",
        "Hovik Keuchkerian",
        "Luka Peroš",
        "Belén Cuesta",
        "Fernando Cayo",
        "Rodrigo de la Serna",
        "Najwa Nimri",
        "Fernando Soto",
        "Mario de la Rosa",
        "Antonio Romero",
        "Mikel Bustamante",
        "José Manuel Seda",
        "Ramón Agirre",
        "Alba Flores",
        "Enrique Arce",
        "Patrick Criado",
        "Diana Gómez",
        "Miguel Ángel Silvestre",
        "Paco Tous",
        "José Manuel Poga",
        "Kiti Mánver",
        "María Pedraza"
      ],
      "type": "5 Parts",
      "description": "This critically acclaimed series, praised by Film Daily as \"the most addictive show on TV,\" won Best Drama at the International Emmys and the Premios Fénix.",
      "chinese": "紙房子",
      "tags_no": [100055, 100041],
      "genres_no": [26146, 81399657, 89811]
    },
    {
      "videoid": "88fb0b5d",
      "title": "Haunted",
      "director": [],
      "cast": [],
      "type": "3 Seasons",
      "description": "Real people. Real stories. Really scary. The things they've seen are horrible ... and continue to haunt them.",
      "chinese": "目擊超自然",
      "tags_no": [100053],
      "genres_no": [100053]
    },
    {
      "videoid": "d8de37db",
      "title": "Night Stalker: The Hunt for a Serial Killer",
      "director": ["Tiller Russell"],
      "cast": [],
      "type": "Limited Series",
      "description": "A series of murders, rapes and kidnappings baffles police until detectives Gil Carrillo and Frank Salerno team up and start connecting the crimes.",
      "chinese": "夜行者：極惡連環殺手",
      "tags_no": [3053904],
      "genres_no": [3053904]
    },
    {
      "videoid": "1ca4288a",
      "title": "The End of the F***ing World",
      "director": [],
      "cast": [
        "Jessica Barden",
        "Alex Lawther",
        "Naomi Ackie",
        "Jonathan Aris",
        "Nadine Marshall",
        "Karl Collins",
        "Steve Oram",
        "Christine Bottomley",
        "Navin Chowdhry",
        "Wunmi Mosaku",
        "Gemma Whelan",
        "Eileen Davies"
      ],
      "type": "2 Seasons",
      "description": "This comedy-drama series based on the graphic novel by Charles Forsman features Alex Lawther and Jessica Barden.",
      "chinese": "去 X 的世界末日",
      "tags_no": [1632671],
      "genres_no": [81399656, 60951, 11714]
    },
    {
      "videoid": "1ee206b8",
      "title": "After Life",
      "director": ["Ricky Gervais"],
      "cast": [
        "Ricky Gervais",
        "Tom Basden",
        "Tony Way",
        "Diane Morgan",
        "Mandeep Dhillon",
        "David Bradley",
        "Ashley Jensen",
        "Kerry Godliman",
        "Penelope Wilton",
        "Jo Hartley",
        "Paul Kaye",
        "Roisin Conaty",
        "Joe Wilkinson",
        "David Earl",
        "Ethan Lawrence",
        "Kath Hughes"
      ],
      "type": "3 Seasons",
      "description": "This darkly comedic drama series about a widower struggling with the meaning of life was created by and stars Ricky Gervais.",
      "chinese": "終極後人生",
      "tags_no": [100060],
      "genres_no": [81399656, 11714, 10375]
    },
    {
      "videoid": "e5ac0ea2",
      "title": "The Victims' Game",
      "director": ["David Chuang", "Chen Kuan-chung"],
      "cast": [
        "Joseph Chang",
        "Hsu Wei-ning",
        "Jason Wang",
        "Ruby Lin",
        "Moon Lee",
        "River Huang",
        "Chen Chia-kuei",
        "Ding Ning",
        "Hsia Ching-ting",
        "Cheng Jen-shuo",
        "Chang Zhang-xing"
      ],
      "type": "1 Season",
      "description": "A man is torn between justice and fatherly love. And he must find the perpetrators before they become the next victims.",
      "chinese": "誰是被害者",
      "tags_no": [100055],
      "genres_no": [81417804, 4366, 26146]
    },
    {
      "videoid": "d9cbd1b9",
      "title": "Orphan",
      "director": ["Jaume Collet-Serra"],
      "cast": [
        "Vera Farmiga",
        "Peter Sarsgaard",
        "Isabelle Fuhrman",
        "CCH Pounder",
        "Jimmy Bennett",
        "Margo Martindale",
        "Karel Roden",
        "Aryana Engineer"
      ],
      "type": "2h 2m",
      "description": "Kate and John Coleman adopt 9-year-old Esther from an orphanage, but it doesn't take long for Kate to see through Esther's angelic façade.",
      "chinese": "孤兒怨",
      "tags_no": [1159493, 8711],
      "genres_no": [1159493, 8711]
    },
    {
      "videoid": "2a17b7d2",
      "title": "Gone Girl",
      "director": ["David Fincher"],
      "cast": [
        "Ben Affleck",
        "Rosamund Pike",
        "Neil Patrick Harris",
        "Tyler Perry",
        "Carrie Coon",
        "Kim Dickens",
        "Patrick Fugit",
        "David Clennon",
        "Lisa Banes",
        "Missi Pyle",
        "Emily Ratajkowski",
        "Casey Wilson",
        "Lola Kirke",
        "Boyd Holbrook",
        "Sela Ward"
      ],
      "type": "2h 28m",
      "description": "His marriage crumbling, Nick comes home one day to find his wife has vanished. And as the police turn up the heat, shocking truths come to light.",
      "chinese": "控制",
      "tags_no": [9994, 1159493, 9889, 5824, 8933],
      "genres_no": [9994, 1159493, 9889]
    },
    {
      "videoid": "9ea88656",
      "title": "Perfume",
      "director": ["Eva Kranenburg", "Philipp Kadelbach", "Oliver Berben"],
      "cast": [
        "Friederike Becht",
        "August Diehl",
        "Wotan Wilke Möhring",
        "Natalia Belitski",
        "Ken Duken",
        "Trystan Pütter",
        "Christian Friedel",
        "Juergen Maurer",
        "Marc Hosemann",
        "Susanne Wuest"
      ],
      "type": "1 Season",
      "description": "When another victim turns up, the police zero in on a suspect. Nadja's lingering doubts -- and a tip from Köhler -- lead to a shocking confrontation.",
      "chinese": "香水",
      "tags_no": [100040, 100037],
      "genres_no": [81417795, 4366, 26146, 1819174, 89811]
    },
    {
      "videoid": "e6a58441",
      "title": "Parasite",
      "director": ["Bong Joon Ho"],
      "cast": [
        "Song Kang-ho",
        "Lee Sun-kyun",
        "Cho Yeo-jeong",
        "Choi Woo-shik",
        "Park So-dam",
        "Lee Jung-eun",
        "Chang Hyae-jin",
        "Park Myung-hoon",
        "Jung Ziso",
        "Jung Hyeon-jun"
      ],
      "type": "2h 6m",
      "description": "A family of have-nots latch onto a chance to thrive off a family of haves. But in truth, leeching goes both ways.",
      "chinese": "寄生上流",
      "tags_no": [81427756, 6548, 8933],
      "genres_no": [81427756, 6548, 8933]
    },
    {
      "videoid": "deaab5da",
      "title": "The Exorcist",
      "director": ["William Friedkin"],
      "cast": [
        "Ellen Burstyn",
        "Jason Miller",
        "Linda Blair",
        "Max von Sydow",
        "Lee J. Cobb",
        "Kitty Winn",
        "Jack MacGowran",
        "William O'Malley",
        "Barton Heyman",
        "Peter Masterson"
      ],
      "type": "2h 1m",
      "description": "Is a little girl still just a little girl if a demon lurks inside her? Two priests pray the answer is \"yes.\"",
      "chinese": "大法師",
      "tags_no": [1159493, 9889, 31574, 8711],
      "genres_no": [1159493, 9889, 31574]
    },
    {
      "videoid": "84d67fa3",
      "title": "Locke & Key",
      "director": [],
      "cast": [
        "Darby Stanchfield",
        "Connor Jessup",
        "Emilia Jones",
        "Jackson Robert Scott",
        "Petrice Jones",
        "Laysla De Oliveira",
        "Griffin Gluck",
        "Aaron Ashmore",
        "Brendan Hines",
        "Hallea Jones",
        "Sherri Saum",
        "Bill Heck",
        "Genevieve Kang",
        "Kevin Alves",
        "Thomas Mitchell Barnet",
        "Eric Graise",
        "Felix Mallard",
        "Martin Roach",
        "Asha Bromfield",
        "Steven Williams",
        "Coby Bird",
        "Jesse Camacho",
        "Joy Tanner",
        "Liyou Abere"
      ],
      "type": "2 Seasons",
      "description": "While Nina uncovers details about Rendell's past, Kinsey helps out the Savini Squad, Tyler falls in with a bad crowd, and Bode finds another key.",
      "chinese": "致命鑰匙",
      "tags_no": [100049, 100060],
      "genres_no": [1002031, 60951, 11714]
    },
    {
      "videoid": "470c7a89",
      "title": "The Butterfly Effect",
      "director": ["Eric Bress", "J. Mackye Gruber"],
      "cast": [
        "Ashton Kutcher",
        "Amy Smart",
        "Eric Stoltz",
        "William Lee Scott",
        "Elden Henson",
        "Logan Lerman",
        "John Patrick Amedori",
        "Melora Walters",
        "Ethan Suplee",
        "Irina Gorovaia",
        "Kevin G. Schmidt"
      ],
      "type": "1h 53m",
      "description": "A haunted youth learns how to change his terrible past. But the truth he finds might not be what he wants.",
      "chinese": "蝴蝶效應",
      "tags_no": [2300970, 1159493, 8933],
      "genres_no": [3276033, 1159493, 8933]
    },
    {
      "videoid": "319232a9",
      "title": "Someone Has to Die",
      "director": ["Manolo Caro"],
      "cast": ["Manolo Caro"],
      "type": "Limited Series",
      "description": "In conservative 1950s Spain, the alleged relationship between a young man and a Mexican ballerino creates an uproar of harrowing consequences.",
      "chinese": "有人必須死",
      "tags_no": [26146, 81399657, 89811, 11714],
      "genres_no": [26146, 81399657, 89811]
    },
    {
      "videoid": "bf3b7fde",
      "title": "The Queen's Gambit",
      "director": ["Scott Frank", "Allan Scott"],
      "cast": [
        "Anya Taylor-Joy",
        "Bill Camp",
        "Marielle Heller",
        "Thomas Brodie-Sangster",
        "Moses Ingram",
        "Harry Melling",
        "Isla Johnston",
        "Christiane Seidel",
        "Rebecca Root",
        "Chloe Pirrie",
        "Jacob Fortune-Lloyd"
      ],
      "type": "Limited Series",
      "description": "Sent to an orphanage at age 9, Beth develops an uncanny knack for chess — and a growing dependence on the green tranquilizers given to the children.",
      "chinese": "后翼棄兵",
      "tags_no": [100033, 3066432, 100039],
      "genres_no": [1819174, 2691116, 11714]
    },
    {
      "videoid": "7e2d47f6",
      "title": "A Brighter Summer Day",
      "director": ["Edward Yang"],
      "cast": ["Chang Chen", "Lisa Yang", "Chang Kuo-chu", "Elaine Jin"],
      "type": "3h 56m",
      "description": "In 1960s Taiwan, a teenage boy and the girl he loves confront gang violence, cultural upheaval and their own mutable sense of identity.",
      "chinese": "牯嶺街少年殺人事件",
      "tags_no": [81417804, 920, 5763],
      "genres_no": [81417804, 920, 5763]
    },
    {
      "videoid": "39e4e1b2",
      "title": "Insidious: Chapter 3",
      "director": ["Leigh Whannell"],
      "cast": [
        "Dermot Mulroney",
        "Stefanie Scott",
        "Lin Shaye",
        "Angus Sampson",
        "Leigh Whannell",
        "Tate Berney",
        "Michael Reid MacKay",
        "Steve Coulter",
        "Hayley Kiyoko",
        "Corbett Tuck"
      ],
      "type": "1h 37m",
      "description": "When psychic Elise Rainier reluctantly agrees to help a teen contact her deceased mother, she unwittingly unleashes a demon that torments the girl.",
      "chinese": "陰兒房第 3 章：從靈開始",
      "tags_no": [1159493, 8711],
      "genres_no": [1159493, 8711]
    },
    {
      "videoid": "a3079261",
      "title": "The Women and the Murderer",
      "director": ["Mona Achache", "Patricia Tourancheau"],
      "cast": [],
      "type": "1h 32m",
      "description": "This documentary traces the capture of serial killer Guy Georges through the tireless work of two women: a police chief and a victim's mother.",
      "chinese": "緝兇英雌：巴黎連環殺人事件",
      "tags_no": [100039],
      "genres_no": [100039]
    },
    {
      "videoid": "e93aea82",
      "title": "House of Wax",
      "director": ["Jaume Collet-Serra"],
      "cast": [
        "Elisha Cuthbert",
        "Chad Michael Murray",
        "Paris Hilton",
        "Brian Van Holt",
        "Jared Padalecki",
        "Jon Abrahams",
        "Damon Herriman",
        "Robert Richard",
        "Dragitsa Debert",
        "Thomas Adamson",
        "Murray Smith"
      ],
      "type": "1h 52m",
      "description": "A group of friends making their way to a college football game fall prey to two bloodthirsty brothers in an abandoned small town.",
      "chinese": "恐怖蠟像館",
      "tags_no": [1159493, 8711],
      "genres_no": [1159493, 8711]
    },
    {
      "videoid": "47e562a5",
      "title": "I'm Thinking of Ending Things",
      "director": ["Charlie Kaufman"],
      "cast": [
        "Jessie Buckley",
        "Jesse Plemons",
        "Toni Collette",
        "David Thewlis",
        "Guy Boyd"
      ],
      "type": "2h 14m",
      "description": "On her way to meet his parents, something isn't right. Not with her boyfriend, or his family, or her own fragmenting reality.",
      "chinese": "我想結束這一切",
      "tags_no": [1159493, 9889, 5763, 7077],
      "genres_no": [1159493, 9889, 5763]
    },
    {
      "videoid": "7fd6f4e8",
      "title": "Fight Club",
      "director": ["David Fincher"],
      "cast": [
        "Brad Pitt",
        "Edward Norton",
        "Helena Bonham Carter",
        "Meat Loaf",
        "Jared Leto",
        "Zach Grenier",
        "Holt McCallany",
        "Eion Bailey"
      ],
      "type": "2h 19m",
      "description": "Dissatisfied with life? Try something different -- and a bit brutal. Just never forget the first rule of Fight Club ...",
      "chinese": "鬥陣俱樂部",
      "tags_no": [100037],
      "genres_no": [3947, 1159493, 9889]
    },
    {
      "videoid": "59a2b0a6",
      "title": "The Bridge Curse",
      "director": ["Lester Hsi"],
      "cast": [
        "JC Lin",
        "Vera Yen",
        "Summer Meng",
        "Chang Ning",
        "Ruby Zhan",
        "Hsieh Yi-hung",
        "Cheng Ko"
      ],
      "type": "1h 27m",
      "description": "A group of university students decides to test an urban legend about the ghost of a female student that haunts a campus bridge.",
      "chinese": "女鬼橋",
      "tags_no": [108910, 108911, 100053],
      "genres_no": [81417804, 9994, 8711]
    },
    {
      "videoid": "cd12841d",
      "title": "The Fearless",
      "director": [],
      "cast": [
        "Lego Lee",
        "Jian Man-shu",
        "Jason King",
        "Da-wen",
        "Tai-bao",
        "Kevin Lin",
        "Jean Guo",
        "Ryan Hsu",
        "Zhu You-cheng"
      ],
      "type": "1 Season",
      "description": "A reborn triad man with an ability to see the dead teams up with a forensic expert to solve mysterious crimes.",
      "chinese": "靈異街 11 號",
      "tags_no": [108910, 100054, 100055],
      "genres_no": [81417804, 4366, 26146]
    },
    {
      "videoid": "04e7b814",
      "title": "Formosa 1867",
      "director": ["Tsao Jui-yuan"],
      "cast": [
        "Wu Kang-ren",
        "Wen Chen-ling",
        "Fabio Grangeon",
        "Andrew Chau",
        "Camake Valaule",
        "Msiswagger Zingrur",
        "Jag Huang",
        "Sean Huang",
        "Lei Hung",
        "Hsia Ching-ting"
      ],
      "type": "1 Season",
      "description": "This series reconstructs the history of the fatal Rover Incident in 1867 when the U.S. sent a military expedition to investigate a shipwreck in Taiwan.",
      "chinese": "斯卡羅",
      "tags_no": [100044],
      "genres_no": [81417804, 1819174, 12123]
    },
    {
      "videoid": "7e4b0bfb",
      "title": "Close Your Eyes Before It’s Dark",
      "director": [],
      "cast": [
        "Bryan Chang",
        "Jian Man-shu",
        "Yen Tsao",
        "Sun Ke-fang",
        "Allen Chen",
        "Jake Hsu",
        "Chu Sheng-ping",
        "Blue Lan"
      ],
      "type": "1 Season",
      "description": "While vacationing at a mountain cabin, a group of longtime friends uncovers an old scandal that could have deadly consequences.",
      "chinese": "植劇場：天黑請閉眼",
      "tags_no": [100055],
      "genres_no": [81417804, 89811, 11714]
    },
    {
      "videoid": "9c96c3be",
      "title": "American Murder: The Family Next Door",
      "director": ["Jenny Popplewell"],
      "cast": [],
      "type": "1h 23m",
      "description": "Using raw, firsthand footage, this documentary examines the disappearance of Shanann Watts and her children, and the terrible events that followed.",
      "chinese": "美國殺人檔案：鄰家好爸爸",
      "tags_no": [108911, 3053904, 100039],
      "genres_no": [108911, 3053904, 100039]
    },
    {
      "videoid": "b05809fe",
      "title": "The Invisible Guest",
      "director": ["Oriol Paulo"],
      "cast": [
        "Mario Casas",
        "Ana Wagener",
        "José Coronado",
        "Bárbara Lennie",
        "Francesc Orella",
        "Paco Tous",
        "David Selvas"
      ],
      "type": "1h 46m",
      "description": "After waking next to his now-dead lover in a hotel room, a young businessman hires a prominent lawyer to figure out how he ended up a murder suspect.",
      "chinese": "佈局",
      "tags_no": [100033, 100055],
      "genres_no": [9994, 81399657, 5824]
    },
    {
      "videoid": "60543567",
      "title": "Evil Genius: the True Story of America's Most Diabolical Bank Heist",
      "director": ["Barbara Schroeder"],
      "cast": [],
      "type": "Limited Series",
      "description": "A bank robbery in Pennsylvania ends in the bombing death of a pizza deliveryman who may or may not have been a hostage forced to commit the crime.",
      "chinese": "天才惡魔：披薩炸彈客",
      "tags_no": [108393, 3053904],
      "genres_no": [108393, 3053904]
    },
    {
      "videoid": "6e5569a8",
      "title": "It's Kind of a Funny Story",
      "director": ["Anna Boden", "Ryan Fleck"],
      "cast": [
        "Keir Gilchrist",
        "Emma Roberts",
        "Viola Davis",
        "Lauren Graham",
        "Jim Gaffigan",
        "Zoë Kravitz",
        "Zach Galifianakis",
        "Aasif Mandvi",
        "Lou Myers",
        "Jeremy Davies"
      ],
      "type": "1h 41m",
      "description": "A teenager in crisis checks into a psych ward but does he belong there? A bearded stranger may have all the answers.",
      "chinese": "說來有點可笑",
      "tags_no": [1159493, 9889, 6548, 5763, 7077],
      "genres_no": [1159493, 9889, 6548]
    },
    {
      "videoid": "4770c38d",
      "title": "Fear Street Part 1: 1994",
      "director": ["Leigh Janiak"],
      "cast": [
        "Kiana Madeira",
        "Olivia Scott Welch",
        "Benjamin Flores Jr.",
        "Julia Rehwald",
        "Fred Hechinger",
        "Ashley Zukerman",
        "Maya Hawke",
        "Darrell Britt-Gibson",
        "Jordana Spiro",
        "Jordyn DiNatale"
      ],
      "type": "1h 47m",
      "description": "Chat rooms, mix tapes, murders at the mall. A killer '90s soundtrack fuels this throwback horror flick packed with slasher kills and jump-scare thrills.",
      "chinese": "恐懼大街 1：1994",
      "tags_no": [5977, 1159493, 2340, 8711],
      "genres_no": [5977, 1159493, 2340]
    },
    {
      "videoid": "2a4593c1",
      "title": "Dead Silence",
      "director": ["James Wan"],
      "cast": [
        "Ryan Kwanten",
        "Amber Valletta",
        "Donnie Wahlberg",
        "Michael Fairman",
        "Joan Heney",
        "Bob Gunton",
        "Laura Regan",
        "Dmitry Chepovetsky",
        "Judith Roberts",
        "Keir Gilchrist"
      ],
      "type": "1h 29m",
      "description": "In the face of terror, staying quiet is nearly impossible. But if she hears you ... you'll never say another word.",
      "chinese": "歡迎光臨死亡小鎮",
      "tags_no": [1159493, 8711],
      "genres_no": [1159493, 8711]
    },
    {
      "videoid": "0ad842dc",
      "title": "Gold Leaf",
      "director": ["Lin Chun-yang"],
      "cast": [
        "Cindy Lien",
        "Kuo Tzu-Chien",
        "James Wen",
        "Simon Hsueh",
        "Wilson Hsu",
        "Jag Huang",
        "Sophia Li"
      ],
      "type": "1 Season",
      "description": "In 1949, the only daughter of Taiwan's largest tea exporter decides take charge of the indebted business rather than handing everything over to a man.",
      "chinese": "茶金",
      "tags_no": [100045],
      "genres_no": [81417804, 11714]
    },
    {
      "videoid": "f07b66ed",
      "title": "The Tag-Along: The Devil Fish",
      "director": ["David Chuang"],
      "cast": [
        "Vivian Hsu",
        "Cheng Jen-shuo",
        "Chang Shu-wei",
        "Wu Zhi-xuan",
        "Lung Shao-hua",
        "Francesca Kao"
      ],
      "type": "1h 53m",
      "description": "Two students team up with a medium after accidentally catching a demon fish and releasing evil spirits into the world. Based on a Taiwanese urban legend.",
      "chinese": "人面魚: 紅衣小女孩外傳",
      "tags_no": [81417804, 8711],
      "genres_no": [81417804, 8711]
    },
    {
      "videoid": "ecb5ee4a",
      "title": "Annabelle Comes Home",
      "director": ["Gary Dauberman"],
      "cast": [
        "Mckenna Grace",
        "Madison Iseman",
        "Katie Sarife",
        "Michael Cimino",
        "Samara Lee",
        "Vera Farmiga",
        "Patrick Wilson"
      ],
      "type": "1h 46m",
      "description": "A devilish doll presides over a haunted house of horrors, awakening evil spirits in the home of two demonologists and terrorizing their young daughter.",
      "chinese": "安娜貝爾回家囉",
      "tags_no": [1159493, 8711],
      "genres_no": [1159493, 8711]
    },
    {
      "videoid": "5dc81f93",
      "title": "Memento",
      "director": ["Christopher Nolan"],
      "cast": [
        "Guy Pearce",
        "Carrie-Anne Moss",
        "Joe Pantoliano",
        "Mark Boone Junior",
        "Stephen Tobolowsky",
        "Harriet Sansom Harris",
        "Callum Keith Rennie",
        "Larry Holden"
      ],
      "type": "1h 53m",
      "description": "Suffering short-term memory loss after a head injury, Leonard Shelby embarks on a grim quest to find the lowlife who murdered his wife.",
      "chinese": "記憶拼圖",
      "tags_no": [9994, 1159493, 5824, 8933, 7077],
      "genres_no": [9994, 1159493, 5824]
    },
    {
      "videoid": "1c94a0eb",
      "title": "Hollywood",
      "director": ["Ryan Murphy", "Ian Brennan"],
      "cast": [
        "David Corenswet",
        "Jeremy Pope",
        "Darren Criss",
        "Patti LuPone",
        "Jim Parsons",
        "Laura Harrier",
        "Joe Mantello",
        "Dylan McDermott",
        "Jake Picking",
        "Holland Taylor",
        "Samara Weaving"
      ],
      "type": "1 Season",
      "description": "While waiting for his big break, aspiring movie star Jack Castello accepts a job at a local service station that pumps more than just gas.",
      "chinese": "好萊塢",
      "tags_no": [100040],
      "genres_no": [2691116, 11714, 72404]
    },
    {
      "videoid": "b4a45bbe",
      "title": "Jeffrey Epstein: Filthy Rich",
      "director": [],
      "cast": [],
      "type": "Limited Series",
      "description": "Survivors recount how Epstein abused, manipulated and silenced them as he ran a so-called molestation \"pyramid scheme\" out of his Palm Beach mansion.",
      "chinese": "傑佛瑞·艾普斯坦：上流濁水",
      "tags_no": [3053904],
      "genres_no": [3053904]
    },
    {
      "videoid": "2c1a7114",
      "title": "The Power of the Dog",
      "director": ["Jane Campion"],
      "cast": [
        "Benedict Cumberbatch",
        "Kirsten Dunst",
        "Jesse Plemons",
        "Kodi Smit-McPhee",
        "Frances Conroy",
        "Keith Carradine",
        "Thomasin McKenzie",
        "Geneviève Lemon"
      ],
      "type": "2h 8m",
      "description": "Filmmaker Jane Campion's \"exquisitely crafted\" drama starring Benedict Cumberbatch is \"driven by transfixing performances,\" raves The Hollywood Reporter.",
      "chinese": "犬山記",
      "tags_no": [1159493, 7700, 9889, 5763],
      "genres_no": [1159493, 7700, 9889]
    },
    {
      "videoid": "24709b09",
      "title": "The Falls",
      "director": ["Chung Mong-hong"],
      "cast": [
        "Alyssa Chia",
        "Gingle Wang",
        "Chen Yi-wen",
        "Lee Lee-zen",
        "Renzo Liu",
        "Yang Li-yin",
        "Sung Shao-ching",
        "Waa Wei"
      ],
      "type": "2h 9m",
      "description": "After having to quarantine together during COVID-19, a mother and daughter are forced to confront their personal obstacles and relationship tensions.",
      "chinese": "瀑布",
      "tags_no": [81417804, 5763],
      "genres_no": [81417804, 5763]
    },
    {
      "videoid": "4e0d7c6a",
      "title": "The Midnight Gospel",
      "director": ["Pendleton Ward", "Duncan Trussell"],
      "cast": [
        "Duncan Trussell",
        "Phil Hendrie",
        "Drew Pinsky",
        "Joey Diaz",
        "Natasha Leggero",
        "Johnny Pemberton",
        "Christina Pazsitzky",
        "Anne Lamott",
        "Damien Echols",
        "Trudy Goodman",
        "Maria Bamford",
        "Pauly Shore",
        "Doug Lussenhop",
        "David Nichtern",
        "Steve Little",
        "Caitlin Doughty",
        "Stephen Root"
      ],
      "type": "1 Season",
      "description": "His curiosity's as cosmic as the mind. And it's fed by a wild universe, home to intelligent beings who have stories to share.",
      "chinese": "午夜福音",
      "tags_no": [100049, 1632671, 100033],
      "genres_no": [10375, 72404]
    },
    {
      "videoid": "9232a1ae",
      "title": "Mirage",
      "director": ["Oriol Paulo"],
      "cast": [
        "Adriana Ugarte",
        "Chino Darín",
        "Javier Gutiérrez",
        "Álvaro Morte",
        "Nora Navas",
        "Miquel Fernández",
        "Clara Segura",
        "Mima Riera",
        "Aina Clotet",
        "Albert Pérez",
        "Julio Bohigas-Couto",
        "Belén Rueda"
      ],
      "type": "2h 9m",
      "description": "When a caring nurse alters the past to save a life, her present reality shifts to a new timeline — one without her beloved daughter.",
      "chinese": "幻象",
      "tags_no": [2300970, 81399657, 5824, 5763, 8933],
      "genres_no": [3276033, 81399657, 5824]
    },
    {
      "videoid": "41c2bd53",
      "title": "Long Shot",
      "director": ["Jacob LaMendola"],
      "cast": [],
      "type": "40m",
      "description": "When Juan Catalan is arrested for a murder he didn't commit, he builds his case for innocence around raw footage from a popular TV show. A documentary.",
      "chinese": "意外在場",
      "tags_no": [108393, 3053904],
      "genres_no": [108393, 3053904]
    },
    {
      "videoid": "a7dc9d69",
      "title": "1922",
      "director": ["Zak Hilditch"],
      "cast": [
        "Thomas Jane",
        "Molly Parker",
        "Dylan Schmid",
        "Kaitlyn Bernard",
        "Bob Frazer",
        "Brian d'Arcy James",
        "Neal McDonough"
      ],
      "type": "1h 42m",
      "description": "Coveting his intractable wife's land, he commits an unspeakable crime and inherits it all. Still, a price must be paid.",
      "chinese": "1922",
      "tags_no": [1159493, 12123, 9889, 5824, 5763],
      "genres_no": [1159493, 12123, 9889]
    },
    {
      "videoid": "4d77e988",
      "title": "The Paramedic",
      "director": ["Carles Torras"],
      "cast": [
        "Mario Casas",
        "Déborah François",
        "Guillermo Pfening",
        "María Rodríguez Soto",
        "Celso Bugallo",
        "Raúl Jiménez",
        "Pol Monen",
        "Alice Bocchi",
        "Martín Bacigalupo"
      ],
      "type": "1h 34m",
      "description": "A freak accident. An unhinged mind. Nothing is off the table when it comes to keeping his beloved close. Really close.",
      "chinese": "藥命救護",
      "tags_no": [81399657, 5824, 5763, 8933],
      "genres_no": [81399657, 5824, 5763]
    },
    {
      "videoid": "4283527d",
      "title": "How to Become a Tyrant",
      "director": [],
      "cast": ["Peter Dinklage"],
      "type": "1 Season",
      "description": "This 2021 political documentary series about despots is narrated by Peter Dinklage.",
      "chinese": "暴君養成指引",
      "tags_no": [100037],
      "genres_no": [81562604, 7018, 4006]
    },
    {
      "videoid": "c62a9d01",
      "title": "Man in Love",
      "director": ["Yin Chen-hao"],
      "cast": [
        "Roy Chiu",
        "Hsu Wei-ning",
        "Tsai Chen-nan",
        "Chung Hsin-ling",
        "Lan Wei-hua",
        "Peace Yang",
        "Huang Lu Tz-yin"
      ],
      "type": "1h 55m",
      "description": "When he meets a debt-ridden woman who's caring for her ailing father, a debt collector with a heart of gold sets out to win her love.",
      "chinese": "當男人戀愛時",
      "tags_no": [100050, 100039, 100052],
      "genres_no": [81417804, 5763, 8883]
    },
    {
      "videoid": "56b040c5",
      "title": "A Sun",
      "director": ["Chung Mong-hong"],
      "cast": [
        "Wu Chien-ho",
        "Chen Yi-wen",
        "Samantha Ko",
        "Liu Kuan-ting",
        "Greg Hsu",
        "Wu Tai-ling",
        "Wen Chen-ling",
        "Yin Shin"
      ],
      "type": "2h 35m",
      "description": "A grisly act. A broken family. A tragic loss. The past's unforgiving rays illuminate the road to redemption and acceptance.",
      "chinese": "陽光普照",
      "tags_no": [81417804, 5763],
      "genres_no": [81417804, 5763]
    },
    {
      "videoid": "31da0f91",
      "title": "Fear Street Part 2: 1978",
      "director": ["Leigh Janiak"],
      "cast": [
        "Sadie Sink",
        "Emily Rudd",
        "Ryan Simpkins",
        "McCabe Slye",
        "Ted Sutherland",
        "Jordana Spiro",
        "Gillian Jacobs",
        "Kiana Madeira",
        "Benjamin Flores Jr.",
        "Ashley Zukerman",
        "Olivia Scott Welch",
        "Chiara Aurelia",
        "Jordyn DiNatale"
      ],
      "type": "1h 50m",
      "description": "Terrifying visions. Buried secrets. And so much blood. The mystery of Sarah Fier's curse deepens as a group of camp counselors try to stop a killer.",
      "chinese": "恐懼大街 2：1978",
      "tags_no": [1159493, 2340, 8711],
      "genres_no": [1159493, 2340, 8711]
    },
    {
      "videoid": "d6984e30",
      "title": "The Woman in the Window",
      "director": ["Joe Wright"],
      "cast": [
        "Amy Adams",
        "Gary Oldman",
        "Anthony Mackie",
        "Fred Hechinger",
        "Wyatt Russell",
        "Brian Tyree Henry",
        "Jennifer Jason Leigh",
        "Jeanine Serralles",
        "Mariah Bozeman",
        "Julianne Moore"
      ],
      "type": "1h 41m",
      "description": "Amy Adams leads an all-star cast including Julianne Moore, Anthony Mackie, Wyatt Russell and Gary Oldman in this immersive psychological thriller.",
      "chinese": "窺探",
      "tags_no": [9994, 1159493, 9889, 5824, 5763],
      "genres_no": [9994, 1159493, 9889]
    },
    {
      "videoid": "5590f1dc",
      "title": "Fear Street Part 3: 1666",
      "director": ["Leigh Janiak"],
      "cast": [
        "Kiana Madeira",
        "Ashley Zukerman",
        "Gillian Jacobs",
        "Olivia Scott Welch",
        "Benjamin Flores Jr.",
        "Darrell Britt-Gibson",
        "Sadie Sink",
        "Emily Rudd",
        "McCabe Slye",
        "Julia Rehwald",
        "Fred Hechinger",
        "Jordana Spiro",
        "Jordyn DiNatale"
      ],
      "type": "1h 54m",
      "description": "Dark secrets. Unspeakable evil. The merciless world of 1666 holds the truth behind the curse — and the key to Shadyside’s future.",
      "chinese": "恐懼大街 3：1666",
      "tags_no": [5977, 1159493, 2340, 8711],
      "genres_no": [5977, 1159493, 2340]
    },
    {
      "videoid": "bf8ae762",
      "title": "Surviving Death",
      "director": [],
      "cast": [],
      "type": "1 Season",
      "description": "The Guardian hails this series as building “a convincing and provocative case that our consciousness can and does continue beyond life as we know it.\"",
      "chinese": "死而未亡：彼岸的世界",
      "tags_no": [100049, 108393, 3053904],
      "genres_no": [100049, 108393, 3053904]
    },
    {
      "videoid": "f00b3d0d",
      "title": "November 13: Attack on Paris",
      "director": ["Gedeon Naudet", "Jules Naudet"],
      "cast": [],
      "type": "Limited Series",
      "description": "It began as a night of celebration -- and ended in devastation. An intimate look at a city's humanity, loss and resilience.",
      "chinese": "1113 巴黎恐攻",
      "tags_no": [3053904, 100039],
      "genres_no": [3053904, 100039]
    },
    {
      "videoid": "6520dc93",
      "title": "Hate the Sin, Love the Sinner",
      "director": [],
      "cast": [
        "Kaiser Chuang",
        "Yen Tsao",
        "Kimi Hsia",
        "Janel Tsai",
        "Phoebe Lin",
        "Ying Tsai-ling",
        "Jonathan Na",
        "Chen Wen-shan",
        "Chris Lung",
        "Yan Yu-lin"
      ],
      "type": "1 Season",
      "description": "Love, loyalty and a life-altering decision. If they can't change the past, can they change the truth?",
      "chinese": "噬罪者",
      "tags_no": [100039],
      "genres_no": [81417804, 26146, 11714]
    },
    {
      "videoid": "3ffa2f36",
      "title": "World's Most Wanted",
      "director": [],
      "cast": [],
      "type": "1 Season",
      "description": "Suspected of heinous crimes, they’ve avoided capture despite massive rewards and global investigations. A docuseries profiling the world’s most wanted.",
      "chinese": "全球頭號通緝犯",
      "tags_no": [108393, 3053904],
      "genres_no": [108393, 3053904]
    },
    {
      "videoid": "ab34cc8a",
      "title": "Disenchantment",
      "director": ["Matt Groening"],
      "cast": [
        "Abbi Jacobson",
        "Eric André",
        "Nat Faxon",
        "John DiMaggio",
        "Tress MacNeille",
        "Matt Berry",
        "David Herman",
        "Maurice LaMarche",
        "Lucy Montgomery",
        "Billy West",
        "Richard Ayoade"
      ],
      "type": "4 Parts",
      "description": "Lonely Zøg searches the forest for his true love, Ursula the Bear, who's got a secret. Elfo, Luci and Bean stumble upon the site of an ancient battle.",
      "chinese": "崩壞夢王國",
      "tags_no": [100060],
      "genres_no": [1002031, 10375, 72404]
    },
    {
      "videoid": "e7a1e4f1",
      "title": "Eat Pray Love",
      "director": ["Ryan Murphy"],
      "cast": [
        "Julia Roberts",
        "James Franco",
        "Javier Bardem",
        "Richard Jenkins",
        "Viola Davis",
        "Billy Crudup",
        "Hadi Subiyanto",
        "Mike O'Malley",
        "Tuva Novotny",
        "Luca Argentero"
      ],
      "type": "2h 20m",
      "description": "From Italy to India to Bali, one writer searches for meaning. But how far do you have to go to find yourself?",
      "chinese": "享受吧！一個人的旅行",
      "tags_no": [920, 1159493, 9889, 5763, 8883],
      "genres_no": [920, 1159493, 9889]
    },
    {
      "videoid": "369bde32",
      "title": "Tear Along the Dotted Line",
      "director": ["Zerocalcare"],
      "cast": [
        "Zerocalcare",
        "Valerio Mastandrea",
        "Paolo Vivio",
        "Chiara Gioncardi",
        "Veronica Puccio"
      ],
      "type": "1 Season",
      "description": "A cartoonist in Rome with his armadillo-for-a-conscience reflects on his path in life and a would-be love as he and his friends travel outside the city.",
      "chinese": "人生的輪廓",
      "tags_no": [1632671],
      "genres_no": [81417798, 2192320, 10375]
    },
    {
      "videoid": "36c9deaa",
      "title": "On Children",
      "director": [],
      "cast": [
        "Chuan-Chen Yeh",
        "Chung Hsin-ling",
        "Frances Wu",
        "Cherry Hsieh",
        "Ko Su-yun",
        "Ivy Yin",
        "Gingle Wang",
        "Hsiu-Fu Liu",
        "Tzu-Chuan Liu",
        "Yu-Xuan Wang"
      ],
      "type": "1 Season",
      "description": "Hostage to test scores. Tyrannized by motherly attention. Their lives are no longer their own -- and they must measure up.",
      "chinese": "你的孩子不是你的孩子",
      "tags_no": [100049, 100033],
      "genres_no": [81417804, 3300242, 1819174]
    },
    {
      "videoid": "39ef846d",
      "title": "The Politician",
      "director": ["Ryan Murphy", "Brad Falchuk", "Ian Brennan"],
      "cast": [
        "Ben Platt",
        "Gwyneth Paltrow",
        "Jessica Lange",
        "Judith Light",
        "Bette Midler",
        "Lucy Boynton",
        "Zoey Deutch",
        "Julia Schlaepfer",
        "Laura Dreyfuss",
        "Theo Germaine",
        "Rahne Jones",
        "Bob Balaban",
        "David Corenswet",
        "Benjamin Barrett"
      ],
      "type": "2 Seasons",
      "description": "Ruthless rivals. Sordid scandals. Backstabbing and betrayal. High school is the perfect training for a life in politics.",
      "chinese": "大政治家",
      "tags_no": [100050],
      "genres_no": [25807, 60951, 11714]
    },
    {
      "videoid": "c119b26d",
      "title": "The Boys in the Band",
      "director": ["Joe Mantello"],
      "cast": [
        "Jim Parsons",
        "Zachary Quinto",
        "Matt Bomer",
        "Andrew Rannells",
        "Charlie Carver",
        "Robin de Jesús",
        "Brian Hutchison",
        "Michael Benjamin Washington",
        "Tuc Watkins"
      ],
      "type": "2h 2m",
      "description": "At a birthday party in 1968 New York, a surprise guest and a drunken game leave seven gay friends reckoning with unspoken feelings and buried truths.",
      "chinese": "男孩夜派對",
      "tags_no": [5977, 1159493, 5763],
      "genres_no": [5977, 1159493, 5763]
    },
    {
      "videoid": "470f0306",
      "title": "A Tale Dark & Grimm",
      "director": [],
      "cast": [
        "Raini Rodriguez",
        "Andre Robinson",
        "Jonathan Banks",
        "Scott Adsit",
        "Erica Rhodes",
        "Ron Funches",
        "Eric Bauza",
        "Charlotte Wilson Langley",
        "Nicole Byer",
        "Tom Hollander",
        "David Henrie",
        "Adam Lambert",
        "Missi Pyle"
      ],
      "type": "1 Season",
      "description": "A bestselling book comes to life in this delightfully twisted tale that goes way beyond Hansel and Gretel and the witch with the candy-covered house.",
      "chinese": "暗黑格林童話",
      "tags_no": [100060, 100037],
      "genres_no": [27346, 11177, 1002031]
    },
    {
      "videoid": "7bb64b40",
      "title": "The Curse of La Llorona",
      "director": ["Michael Chaves"],
      "cast": [
        "Linda Cardellini",
        "Raymond Cruz",
        "Patricia Velasquez",
        "Marisol Ramirez",
        "Sean Patrick Thomas",
        "Roman Christou",
        "Jaynee-Lynne Kinchen",
        "Tony Amendola"
      ],
      "type": "1h 33m",
      "description": "In 1970s Los Angeles, a troubled single mother discovers some folktales are true when a dark entity with sinister intentions pursues her children.",
      "chinese": "哭泣的女人",
      "tags_no": [1159493, 8711],
      "genres_no": [1159493, 8711]
    },
    {
      "videoid": "f9851e69",
      "title": "Heaven on the 4th Floor",
      "director": ["Singing Chen"],
      "cast": [
        "Anthony Wong Chau-sang",
        "Hsieh Ying-xuan",
        "Fandy Fan",
        "True Wang",
        "Huang Peijia",
        "Lily Pan",
        "Umin Boya",
        "Chen Chia-kuei"
      ],
      "type": "1 Season",
      "description": "At a massage parlor tucked away on the fourth floor of an apartment building, a Tuina practitioner brings clients both physical and emotional healing.",
      "chinese": "四樓的天堂",
      "tags_no": [100045, 100039],
      "genres_no": [81417804, 11714]
    },
    {
      "videoid": "18713ede",
      "title": "Secrets of the Saqqara Tomb",
      "director": ["James Tovell"],
      "cast": [],
      "type": "1h 54m",
      "description": "After unearthing a tomb that had been untouched for 4,400 years, Egyptian archaeologists attempt to decipher the history of the extraordinary find.",
      "chinese": "薩卡拉陵墓揭秘",
      "tags_no": [100057, 3053904],
      "genres_no": [100057, 3053904]
    },
    {
      "videoid": "afbd995b",
      "title": "Til Death Do Us Part",
      "director": ["MirrorFiction Inc."],
      "cast": [
        "Wen Chen-ling",
        "River Huang",
        "Lin He-xuan",
        "Phoebe Lin",
        "Janel Tsai",
        "Dara Hanfman",
        "Hsia Teng-hung",
        "Nikki Hsieh"
      ],
      "type": "1 Season",
      "description": "Bizarre time loops. Feline trouble. An unstoppable spot. Welcome to a twilit world of both dreams and nightmares.",
      "chinese": "驚悚劇場",
      "tags_no": [100033, 100034],
      "genres_no": [81417804, 89811, 11714]
    },
    {
      "videoid": "ea881c1e",
      "title": "Be Alive Just Like You",
      "director": ["Lai Meng-chieh"],
      "cast": [
        "Cheng Jen-shuo",
        "Ally Chiu",
        "Cheng Chih-wei",
        "Jason King",
        "Alice Huang"
      ],
      "type": "1h 32m",
      "description": "A man with paraplegia and a destitute young woman begin an unusual romance, desperately seeking connection amid the harsh realities of their lives.",
      "chinese": "親愛的殺手",
      "tags_no": [81417804, 5763, 8883],
      "genres_no": [81417804, 5763, 8883]
    },
    {
      "videoid": "eaa37a9a",
      "title": "Enola Holmes",
      "director": ["Harry Bradbeer"],
      "cast": [
        "Millie Bobby Brown",
        "Henry Cavill",
        "Sam Claflin",
        "Helena Bonham Carter",
        "Louis Partridge",
        "Burn Gorman",
        "Adeel Akhtar",
        "Susan Wokoma",
        "Frances de la Tour",
        "Fiona Shaw"
      ],
      "type": "2h 4m",
      "description": "Her mother? Vanished. Her brothers, Sherlock and Mycroft? Vexing. To solve this mystery, she'll go it alone. The game is afoot.",
      "chinese": "天才少女福爾摩斯",
      "tags_no": [9994, 51056, 1159493, 12123, 9889],
      "genres_no": [9994, 51056, 1159493]
    },
    {
      "videoid": "a313f410",
      "title": "Dear Tenant",
      "director": ["Cheng Yu-chieh"],
      "cast": [
        "Mo Tzu Yi",
        "Chen Shu-fang",
        "Bai Run-yin",
        "Yao Chun-yao",
        "Jay Shih",
        "Cherry Hsieh",
        "Wu Pong-fong",
        "Shen Wei-nian",
        "Wang Ko-yuan"
      ],
      "type": "1h 46m",
      "description": "A man looking after his deceased partner's mother and son becomes entangled in a bitter legal battle with the child's uncle.",
      "chinese": "親愛的房客",
      "tags_no": [81417804, 5763],
      "genres_no": [81417804, 5763]
    },
    {
      "videoid": "f05d605a",
      "title": "The Social Dilemma",
      "director": ["Jeff Orlowski"],
      "cast": ["Skyler Gisondo", "Kara Hayward", "Vincent Kartheiser"],
      "type": "1h 34m",
      "description": "This social media exposé premiered at Sundance, winning a pair of Emmys with five additional nominations.",
      "chinese": "智能社會：進退兩難",
      "tags_no": [2243108, 2595, 1159493],
      "genres_no": [2243108, 2595, 1159493]
    },
    {
      "videoid": "f355501f",
      "title": "Beyond Stranger Things",
      "director": [],
      "cast": [
        "Jim Rash",
        "Matt Duffer",
        "Ross Duffer",
        "Shawn Levy",
        "David Harbour",
        "Finn Wolfhard",
        "Millie Bobby Brown",
        "Gaten Matarazzo",
        "Caleb McLaughlin",
        "Natalia Dyer",
        "Charlie Heaton",
        "Noah Schnapp",
        "Joe Keery",
        "Dacre Montgomery",
        "Sadie Sink",
        "Paul Reiser",
        "Sean Astin",
        "Randy Havens",
        "Brett Gelman",
        "Linnea Berthelsen"
      ],
      "type": "1 Volume",
      "description": "Millie Bobby Brown, Finn Wolfhard, Shawn Levy and the Duffer Brothers sit down to discuss new characters and the season's most important themes.",
      "chinese": "怪奇物語外章",
      "tags_no": [108911],
      "genres_no": [3030851, 3300242, 60951]
    },
    {
      "videoid": "6cb7dea6",
      "title": "Derren Brown: The Push",
      "director": [],
      "cast": ["Derren Brown"],
      "type": "1h 9m",
      "description": "Mentalist Derren Brown engineers an audacious social experiment demonstrating how manipulation can lead an ordinary person to commit an appalling act.",
      "chinese": "達倫·布朗：逼迫",
      "tags_no": [108393],
      "genres_no": [81399656, 9833]
    },
    {
      "videoid": "32bef61b",
      "title": "Badla",
      "director": ["Sujoy Ghosh"],
      "cast": [
        "Amitabh Bachchan",
        "Taapsee Pannu",
        "Amrita Singh",
        "Tony Luke",
        "Manav Kaul"
      ],
      "type": "1h 57m",
      "description": "When a woman is accused of killing her lover, a renowned lawyer is hired -- but the more they try to  untangle the truth, the more convoluted it becomes.",
      "chinese": "復仇",
      "tags_no": [9994, 81418683, 58806, 5480, 5824],
      "genres_no": [9994, 81418683, 58806]
    },
    {
      "videoid": "64869afe",
      "title": "Derren Brown: Sacrifice",
      "director": ["John Pereira"],
      "cast": ["Derren Brown"],
      "type": "49m",
      "description": "A master manipulator. A daring social experiment. How far can one man be pushed to save a stranger?",
      "chinese": "達倫·布朗：犧牲",
      "tags_no": [108393],
      "genres_no": [81399656, 9833]
    },
    {
      "videoid": "12bdf641",
      "title": "The Body",
      "director": ["Jeethu Joseph"],
      "cast": [
        "Rishi Kapoor",
        "Emraan Hashmi",
        "Sobhita Dhulipala",
        "Vedika",
        "Anupam Bhattacharya",
        "Chandan Anand",
        "Arif Zakaria",
        "Rukhsar Ahmed"
      ],
      "type": "1h 40m",
      "description": "Mind games and mystery abound as a detective investigates the disappearance of a woman’s body from a morgue in this Hindi remake of a Spanish thriller.",
      "chinese": "疑體",
      "tags_no": [81418683, 58806, 5480, 5824, 8933],
      "genres_no": [81418683, 58806, 5480]
    },
    {
      "videoid": "7e4b5433",
      "title": "Derren Brown: Miracle",
      "director": ["Julia Knowles", "John L. Spencer"],
      "cast": ["Derren Brown"],
      "type": "1h 13m",
      "description": "Illusionist Derren Brown reinvents the concept of \"faith healing” through a series of stunts that debunk the confines of fear, pain and disbelief.",
      "chinese": "達倫·布朗：奇蹟",
      "tags_no": [100060],
      "genres_no": [81399656, 9833]
    },
    {
      "videoid": "74e6a779",
      "title": "Newness",
      "director": ["Drake Doremus"],
      "cast": [
        "Nicholas Hoult",
        "Laia Costa",
        "Danny Huston",
        "Courtney Eaton",
        "Matthew Gray Gubler",
        "Albert Hammond Jr."
      ],
      "type": "1h 57m",
      "description": "A new couple tries to keep monogamy interesting. But the lure of online hookups could be too much to resist.",
      "chinese": "我們的愛情一言難盡",
      "tags_no": [1159493, 5763, 7077, 8883],
      "genres_no": [1159493, 5763, 7077]
    },
    {
      "videoid": "08883de8",
      "title": "Slasher",
      "director": ["Aaron Martin"],
      "cast": [
        "Katie McGrath",
        "Brandon Jay McLaren",
        "Steve Byers",
        "Patrick Garrow",
        "Dean McDermott",
        "Christopher Jacot",
        "Wendy Crewson",
        "Leslie Hope",
        "Lovell Adams-Gray",
        "Jim Watson",
        "Paulino Nunes",
        "Ty Olsson",
        "Joanne Vannicola",
        "Sebastian Pigott",
        "Madison Cheeatow",
        "Melinda Shankar",
        "Kaitlyn Leeb",
        "Rebecca Liddiard",
        "Paula Brancati",
        "Salvatore Antonio",
        "Lisa Berry",
        "Gabriel Darku",
        "Erin Karpluk",
        "Mercedes Morris",
        "Ilan Muallem",
        "Baraka Rahmani",
        "Rosie Simon",
        "Robert Cormier"
      ],
      "type": "3 Seasons",
      "description": "Rampaging serial killers leave carnage in their wake as their next victims fight to stay alive in this horror anthology series.",
      "chinese": "鮮血淋漓",
      "tags_no": [100053],
      "genres_no": [4366, 83059, 72404]
    },
    {
      "videoid": "08e6f7af",
      "title": "Conversations with a Killer: The John Wayne Gacy Tapes",
      "director": ["Joe Berlinger"],
      "cast": [],
      "type": "Limited Series",
      "description": "John Wayne Gacy becomes a prime suspect in teen Robert Piest’s disappearance. Previously unheard audio tapes reveal Gacy’s thoughts and early days.",
      "chinese": "與殺人魔對話：約翰·韋恩·葛西訪談錄",
      "tags_no": [108911],
      "genres_no": [108911]
    },
    {
      "videoid": "a0dabea2",
      "title": "The Movies That Made Us",
      "director": [],
      "cast": [],
      "type": "3 Seasons",
      "description": "We laughed. We cried. We found ourselves at the movies, changed. Now go behind the scenes of these must-see pictures.",
      "chinese": "電影的故事：你我的永恆印象",
      "tags_no": [100054, 100050],
      "genres_no": [100054, 100050]
    },
    {
      "videoid": "24296ba8",
      "title": "Catching Killers",
      "director": [],
      "cast": [],
      "type": "2 Seasons",
      "description": "A terrifying Kansas serial killer reemerges after 30 years. Using DNA technology and help from the media, investigators race to prevent another murder.",
      "chinese": "追緝連環殺手",
      "tags_no": [3053904, 100055],
      "genres_no": [3053904, 100055]
    },
    {
      "videoid": "d73fdca5",
      "title": "Sex Education",
      "director": ["Laurie Nunn"],
      "cast": [
        "Asa Butterfield",
        "Gillian Anderson",
        "Ncuti Gatwa",
        "Emma Mackey",
        "Connor Swindells",
        "Kedar Williams-Stirling",
        "Alistair Petrie",
        "Aimee Lou Wood",
        "Mimi Keene",
        "Chaneil Kular",
        "Tanya Reynolds",
        "Patricia Allison",
        "Mikael Persbrandt",
        "Rakhee Thakrar",
        "Jemima Kirke",
        "Anne-Marie Duff"
      ],
      "type": "3 Seasons",
      "description": "Despite the ministrations of sex therapist mom Jean and encouragement from pal Eric, Otis worries that he can't get it on. He's not the only one.",
      "chinese": "性愛自修室",
      "tags_no": [100051, 100045],
      "genres_no": [81399656, 60951, 11714]
    },
    {
      "videoid": "1695352b",
      "title": "Adventure Beast",
      "director": ["Mark Gravas", "Bradley Trevor Greive"],
      "cast": ["Bradley Trevor Greive", "Danice Cabanela", "Josh Zuckerman"],
      "type": "1 Season",
      "description": "This adult animated comedy series features and is executive produced by Bradley Trevor Greive.",
      "chinese": "野獸活百科",
      "tags_no": [100043],
      "genres_no": [10375, 72404, 10673]
    },
    {
      "videoid": "481c574c",
      "title": "I AM A KILLER",
      "director": [],
      "cast": [],
      "type": "2 Seasons",
      "description": "Death row inmates convicted of capital murder give firsthand accounts of their crimes in this documentary series.",
      "chinese": "我殺人",
      "tags_no": [108393, 100037],
      "genres_no": [108393, 100037]
    },
    {
      "videoid": "e4b92928",
      "title": "Monsters Inside: The 24 Faces of Billy Milligan",
      "director": ["Olivier Megaton"],
      "cast": [],
      "type": "Limited Series",
      "description": "True crime fans will find themselves engrossed in this dark and disturbing case, one of the first to invoke a multiple personality disorder defense.",
      "chinese": "24 個比利",
      "tags_no": [100036, 108393],
      "genres_no": [100036, 108393]
    },
    {
      "videoid": "1d8b8475",
      "title": "Bake Squad",
      "director": [],
      "cast": [],
      "type": "1 Season",
      "description": "The bakers pack the fun and flair into an edible play space, a colossal chocolate dragon egg and other showstoppers for two boys’ joint birthday fest.",
      "chinese": "圓夢烘焙團",
      "tags_no": [100047, 100058],
      "genres_no": [100047, 100058]
    },
    {
      "videoid": "54743325",
      "title": "Worst Roommate Ever",
      "director": [],
      "cast": [],
      "type": "Limited Series",
      "description": "A woman known as Dorothea Puente runs a boarding house for those less fortunate, but her seeming benevolence belies motives that are much darker.",
      "chinese": "恐怖室友全記錄",
      "tags_no": [108911],
      "genres_no": [108911]
    },
    {
      "videoid": "f2e9b64e",
      "title": "PIECES OF HER",
      "director": ["Charlotte Stoudt"],
      "cast": [
        "Toni Collette",
        "Bella Heathcote",
        "Jessica Barden",
        "Joe Dempsie",
        "Omari Hardwick",
        "Jacob Scipio",
        "David Wenham",
        "Gil Birmingham",
        "Aaron Jeffery"
      ],
      "type": "1 Season",
      "description": "Andy's 30th birthday lunch is interrupted by a shocking act of violence. After her mom's stunning response goes viral, a threat emerges in their home.",
      "chinese": "碎片人生",
      "tags_no": [100055, 100039],
      "genres_no": [4366, 26146, 1819174]
    },
    {
      "videoid": "247e10de",
      "title": "Baking Impossible",
      "director": [],
      "cast": ["Justin Willman"],
      "type": "1 Season",
      "description": "For their final mission, the bakineers build tasty bridges that must survive multiple stress tests. The judges select the winning team.",
      "chinese": "不可能的烘焙工程",
      "tags_no": [100050, 100058, 100041],
      "genres_no": [72436, 49266, 2072262]
    },
    {
      "videoid": "73965e6e",
      "title": "The Innocent",
      "director": ["Harlan Coben"],
      "cast": ["Oriol Paulo"],
      "type": "Limited Series",
      "description": "At a club, Mat is dragged into a brawl and his life alters forever when he accidentally kills a man. Years later, happiness finally seems within reach.",
      "chinese": "第二聲鈴響",
      "tags_no": [26146, 81399657, 1819174, 89811, 11714],
      "genres_no": [26146, 81399657, 1819174]
    },
    {
      "videoid": "6103e6ef",
      "title": "I missed you: Director's Cut",
      "director": ["Mag Hsu", "Hsu Chih-yen"],
      "cast": ["Wu Kang-ren", "Eve Ai", "Fu Meng-po", "Lin Mei-hsiu", "9m88"],
      "type": "1h 35m",
      "description": "A workaholic reconnects with two men she blocked on social media five years ago and begins to reflect on her past life choices.",
      "chinese": "我沒有談的那場戀愛：導演剪輯版",
      "tags_no": [81417804, 5763, 8883],
      "genres_no": [81417804, 5763, 8883]
    },
    {
      "videoid": "75709477",
      "title": "The Motive",
      "director": ["Tali Shemesh", "Asaf Sudry"],
      "cast": [],
      "type": "Limited Series",
      "description": "In 1986, police discover a grisly crime scene: a family shot in their beds at point-blank range. The mystery deepens when a sole survivor appears.",
      "chinese": "犯罪動機：以色列少年殺人事件",
      "tags_no": [108393, 3053904],
      "genres_no": [108393, 3053904]
    },
    {
      "videoid": "444a179b",
      "title": "School of Chocolate",
      "director": [],
      "cast": [],
      "type": "1 Season",
      "description": "The chefs create edible illusions, including a planter box with earthy flavors, then form teams to bend chocolate into architectural shapes.",
      "chinese": "巧克力大師班",
      "tags_no": [100058],
      "genres_no": [100058]
    },
    {
      "videoid": "3e28ec17",
      "title": "The Staircase",
      "director": [],
      "cast": [],
      "type": "Limited Series",
      "description": "Following his wife's suspicious death, Michael Peterson speaks about his version of the events while lawyers and expert witnesses prepare for trial.",
      "chinese": "小說家弒妻案",
      "tags_no": [108393, 100037],
      "genres_no": [108393, 100037]
    },
    {
      "videoid": "64058114",
      "title": "The Raincoat Killer: Chasing a Predator in Korea",
      "director": ["John Choi", "Rob Sixsmith"],
      "cast": [],
      "type": "1 Season",
      "description": "Violent killings target wealthy victims around the city. Matching footprints found at each scene suggest a serial murderer on the loose.",
      "chinese": "韓國雨衣殺手：全面追緝柳永哲",
      "tags_no": [100037],
      "genres_no": [100037]
    },
    {
      "videoid": "02bde40d",
      "title": "The Sons of Sam: A Descent into Darkness",
      "director": ["Joshua Zeman"],
      "cast": [],
      "type": "Limited Series",
      "description": "In August 1977, the arrest of David Berkowitz ended New York City's wave of terror. But journalist Maury Terry believed there was more to the story.",
      "chinese": "山姆之子：黑暗深淵",
      "tags_no": [108911],
      "genres_no": [108911]
    },
    {
      "videoid": "e2060c4a",
      "title": "Lupin",
      "director": ["George Kay"],
      "cast": [
        "Omar Sy",
        "Ludivine Sagnier",
        "Clotilde Hesme",
        "Nicole Garcia",
        "Hervé Pierre",
        "Soufiane Guerrab",
        "Antoine Gouy",
        "Fargass Assandé",
        "Vincent Londez",
        "Shirine Boutella"
      ],
      "type": "2 Parts",
      "description": "Years after a tragic injustice, Assane seeks to settle a score — and a debt — by stealing a diamond necklace, but the heist takes an unexpected turn.",
      "chinese": "亞森·羅蘋",
      "tags_no": [100060, 100041],
      "genres_no": [4366, 26146, 81399454]
    },
    {
      "videoid": "df06d71c",
      "title": "John of God: The Crimes of a Spiritual Healer",
      "director": ["Mauricio Dias", "Tatiana Villela"],
      "cast": [],
      "type": "1 Season",
      "description": "Revered for his \"miracles.\" Reviled for his crimes. One psychic had all the power — until brave survivors proved theirs.",
      "chinese": "上帝的約翰：靈療師的罪行",
      "tags_no": [3053904],
      "genres_no": [3053904]
    },
    {
      "videoid": "6eaf4a1f",
      "title": "One of Us Is Lying",
      "director": [],
      "cast": [
        "Annalisa Cochrane",
        "Chibuikem Uche",
        "Marianly Tejada",
        "Cooper van Grootel",
        "Barrett Carnahan",
        "Jess McLeod",
        "Mark McKenna",
        "Melissa Collazo"
      ],
      "type": "1 Season",
      "description": "School's in session as blogger Simon gets set to expose his classmates' deepest secrets. Then a death in detention turns up the heat on four students.",
      "chinese": "看誰在說謊",
      "tags_no": [100055],
      "genres_no": [4366, 26146, 1819174]
    },
    {
      "videoid": "07dd3285",
      "title": "The Chestnut Man",
      "director": [
        "Søren Sveistrup",
        "Dorte W. Høgh",
        "David Sandreuter",
        "Mikkel Serup"
      ],
      "cast": ["Mikkel Serup"],
      "type": "1 Season",
      "description": "Thulin and her reluctant new partner, Hess, investigate a gruesome murder. Politician Rosa Hartung returns to work after her daughter's disappearance.",
      "chinese": "栗子人殺手",
      "tags_no": [81418679, 4366, 26146, 1819174, 2691116],
      "genres_no": [81418679, 4366, 26146]
    },
    {
      "videoid": "75ae792a",
      "title": "Elize Matsunaga: Once Upon a Crime",
      "director": ["Eliza Capai"],
      "cast": [],
      "type": "Limited Series",
      "description": "On a temporary release from prison, Elize details her troubled relationship with Marcos as people close to the case describe the aftermath of the crime.",
      "chinese": "童話公主的罪與罰",
      "tags_no": [108393, 3053904],
      "genres_no": [108393, 3053904]
    },
    {
      "videoid": "db2adb92",
      "title": "Don't F**k with Cats: Hunting an Internet Killer",
      "director": ["Mark Lewis"],
      "cast": [],
      "type": "Limited Series",
      "description": "A shocking online video brings together a widespread internet group of animal lovers out for justice. Their target, meanwhile, has more horrors planned.",
      "chinese": "別惹喵皇：肉搜網際殺手",
      "tags_no": [100036],
      "genres_no": [100036]
    },
    {
      "videoid": "85507cbc",
      "title": "Murder Among the Mormons",
      "director": ["Jared Hess", "Tyler Measom"],
      "cast": [],
      "type": "Limited Series",
      "description": "Three lethal explosions rattle Salt Lake City in 1985 and expose a dark underbelly of religious-document dealing.",
      "chinese": "摩門教謀殺案",
      "tags_no": [3053904],
      "genres_no": [3053904]
    },
    {
      "videoid": "76e69768",
      "title": "Clickbait",
      "director": ["Tony Ayres", "Christian White"],
      "cast": ["Brad Anderson"],
      "type": "Limited Series",
      "description": "How well do you really know the person you love the most? And would you still love them if the world was saying that the version you knew was a lie?",
      "chinese": "致命點擊",
      "tags_no": [4366, 26146, 89811, 11714, 72404],
      "genres_no": [4366, 26146, 89811]
    },
    {
      "videoid": "8212853c",
      "title": "Crime Stories: India Detectives",
      "director": [],
      "cast": [],
      "type": "1 Season",
      "description": "When a stabbing incident kills a mother and leaves her son gravely injured, Bengaluru police trace the steps and the motives of their unusual suspect.",
      "chinese": "犯罪故事：印度重案組",
      "tags_no": [100037],
      "genres_no": [100037]
    },
    {
      "videoid": "a041fc51",
      "title": "House of Secrets: The Burari Deaths",
      "director": ["Leena Yadav"],
      "cast": [],
      "type": "Limited Series",
      "description": "News of 11 family members found dead in their home sparks a local and national frenzy. Perplexed investigators grapple with more questions than answers.",
      "chinese": "邪密滿屋：印度家族集體死亡案",
      "tags_no": [100037, 3053904],
      "genres_no": [100037, 3053904]
    },
    {
      "videoid": "5d83994b",
      "title": "Dear Ex",
      "director": ["Hsu Chih-yen", "Mag Hsu"],
      "cast": ["Roy Chiu", "Hsieh Ying-xuan", "Joseph Huang", "Spark Chen"],
      "type": "1h 39m",
      "description": "A teen navigates a bitter feud between his willful mom and a free-spirited man, who's the lover and insurance beneficiary of his recently deceased dad.",
      "chinese": "誰先愛上他的",
      "tags_no": [81417804, 5475, 5977, 6548, 5763],
      "genres_no": [81417804, 5475, 5977]
    },
    {
      "videoid": "dfd53db0",
      "title": "The Keepers",
      "director": ["Ryan White"],
      "cast": [],
      "type": "Limited Series",
      "description": "Two former students launch a dogged investigation into the cold case of Sister Catherine Cesnik, a nun who was slain in Baltimore in 1969.",
      "chinese": "守護者",
      "tags_no": [100037, 3053904],
      "genres_no": [100037, 3053904]
    },
    {
      "videoid": "1b126a37",
      "title": "Unabomber - In His Own Words",
      "director": ["Mick Grogan"],
      "cast": ["Ted Kaczynski"],
      "type": "1 Season",
      "description": "As his infamy grows, Ted Kaczynski finds his footing as a serial bomber while authorities desperately search for a pattern with his earliest targets.",
      "chinese": "飛機炸彈客：自述",
      "tags_no": [3053904],
      "genres_no": [81562604, 26146, 81050]
    },
    {
      "videoid": "790ace0a",
      "title": "Spotless",
      "director": ["Corinne Marrinan", "Ed McCardie"],
      "cast": [
        "Marc-André Grondin",
        "Denis Ménochet",
        "Miranda Raison",
        "Doug Allen",
        "Liam Garrigan",
        "Ciarán Owens",
        "Kate Magowan",
        "Tanya Fear",
        "Naomi Radcliffe",
        "Lucy Akhurst",
        "Jemma Donovan",
        "Niall Hayes",
        "Brendan Coyle"
      ],
      "type": "1 Season",
      "description": "When his estranged brother Martin resurfaces, crime scene cleaning company owner Jean is pulled into a dangerous world of mobsters and dark secrets.",
      "chinese": "一塵不染",
      "tags_no": [100037, 100055],
      "genres_no": [26146, 81399454, 89811]
    },
    {
      "videoid": "fb44c1ae",
      "title": "Safe",
      "director": ["Harlan Coben"],
      "cast": [
        "Michael C. Hall",
        "Amanda Abbington",
        "Marc Warren",
        "Hannah Arterton",
        "Audrey Fleurot",
        "Nigel Lindsay"
      ],
      "type": "1 Season",
      "description": "When his teenage daughter doesn't return home after a party, Tom Delaney anxiously combs the neighborhood and learns her boyfriend is also missing.",
      "chinese": "我們很安全",
      "tags_no": [100044, 100055],
      "genres_no": [4366, 26146, 81399656]
    },
    {
      "videoid": "26df115a",
      "title": "Hypnotic",
      "director": ["Matt Angel", "Suzanne Coote"],
      "cast": [
        "Kate Siegel",
        "Jason O'Mara",
        "Dulé Hill",
        "Lucie Guest",
        "Jaime M. Callica",
        "Tanja Dixon-Warren",
        "Luc Roderique",
        "Devyn Dalton",
        "Stephanie Cudmore",
        "Jessie Fraser"
      ],
      "type": "1h 29m",
      "description": "Concentrate on the light. Feel the weight of your body. Relinquish control. And let the deadly mind games begin.",
      "chinese": "奪命催眠",
      "tags_no": [1159493, 8933],
      "genres_no": [1159493, 8933]
    }
  ]
  